/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PageIdRouteRouteImport } from './routes/$pageId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PageIdIndexRouteImport } from './routes/$pageId/index'

const PageIdRouteRoute = PageIdRouteRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PageIdIndexRoute = PageIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PageIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$pageId': typeof PageIdRouteRouteWithChildren
  '/$pageId/': typeof PageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$pageId': typeof PageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$pageId': typeof PageIdRouteRouteWithChildren
  '/$pageId/': typeof PageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$pageId' | '/$pageId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$pageId'
  id: '__root__' | '/' | '/$pageId' | '/$pageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageIdRouteRoute: typeof PageIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$pageId': {
      id: '/$pageId'
      path: '/$pageId'
      fullPath: '/$pageId'
      preLoaderRoute: typeof PageIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pageId/': {
      id: '/$pageId/'
      path: '/'
      fullPath: '/$pageId/'
      preLoaderRoute: typeof PageIdIndexRouteImport
      parentRoute: typeof PageIdRouteRoute
    }
  }
}

interface PageIdRouteRouteChildren {
  PageIdIndexRoute: typeof PageIdIndexRoute
}

const PageIdRouteRouteChildren: PageIdRouteRouteChildren = {
  PageIdIndexRoute: PageIdIndexRoute,
}

const PageIdRouteRouteWithChildren = PageIdRouteRoute._addFileChildren(
  PageIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageIdRouteRoute: PageIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
